/*
 Polynomial.js v1.4.0 13/12/2017

 Copyright (c) 2015, Robert Eisele (robert@xarg.org)
 Dual licensed under the MIT or GPL Version 2 licenses.
*/
(function(F){function J(a){return function(){var c=this.coeff,b=[];for(k in c)b.push(+k);if(0===b.length)return"0";b.sort(function(a,d){return a-d});for(var d,f="",p=b.length;p--;){var k=b[p];var e=c[k];d=e;if(null!==d&&void 0!==d)if(n&&d instanceof n){if(0!==d.re){""!==f&&0<d.re&&(f+="+");if(-1===d.re&&0!==k)f+="-";else if(1!==d.re||0===k)f+=d.re;1===k?f+="x":0!==k&&(f+="x^"+k)}0!==d.im&&(""!==f&&0<d.im&&(f+="+"),-1===d.im?f+="-":1!==d.im&&(f+=d.im),f+="i",1===k?f+="x":0!==k&&(f+="x^"+k))}else if(d=
    d.valueOf(),0!==d){""!==f&&0<d&&(f+="+");if(-1===d&&0!==k)f+="-";else if(1!==d||0===k)f+=e[a]?e[a]():e.toString();1===k?f+="x":0!==k&&(f+="x^"+k)}}return""===f?e[a]?e[a]():e.toString():f}}function m(a){var c={};if(null===a||void 0===a)a=0;switch(typeof a){case "object":a.coeff&&(a=a.coeff);if(C&&a instanceof C||n&&a instanceof n||D&&a instanceof D)c[0]=a;else for(var b in a)g.empty(a[b])||(c[b]=g.parse(a[b]));return c;case "number":return{0:g.parse(a)};case "string":for(var d,f;null!==(b=P.exec(a));){f=
    d=1;void 0!==b[4]?(d=b[4],f=0):void 0!==b[2]&&(d=b[2]);var p=b[1];d=String(d).match(/[^*/]+|[*/]/g);p=g.parse(p+d[0]);for(var e=1;e<d.length;e+=2)"*"===d[e]?p=g.mul(p,g.parse(d[e+1]||1)):"/"===d[e]&&(p=g.div(p,g.parse(d[e+1]||1)));d=p;void 0!==b[3]&&(f=parseInt(b[3],10));c[f]=void 0===c[f]?d:g.add(c[f],d)}return c}throw"Invalid Param";}function H(a,c){for(var b={},d=w(a),f=w(c),p=[];d>=f;){var k=b[d-f]=g.div(a[d]||0,c[f]||0),t;for(t in c)a[+t+d-f]=g.sub(a[+t+d-f]||0,g.mul(c[t]||0,k));if(null!==e.trace){var K=
    {};for(t in c)K[+t+d-f]=g.mul(c[t]||0,k);p.push(new e(K))}d=w(a)}null!==e.trace&&(p.push(new e(a)),e.trace=p);return b}function L(a,c){var b=1;for(c=a-c;c<a;a--)b*=a;return b}function e(a){if(!(this instanceof e))return new e(a);this.coeff=m(a)}function E(a){var c={},b;for(b in a)c[b]=a[b];return c}function M(a,c){var b={},d;for(d in a)b[d]=1;for(d in c)b[d]=1;return b}function w(a){var c=Number.NEGATIVE_INFINITY,b;for(b in a)g.empty(a[b])||(c=Math.max(b,c));return c}function G(a){var c=null,b;for(b in a)!g.empty(a[b])&&
    (null===c||+c<+b)&&(c=b);return c}function N(a,c){if(null!==c)for(var b in a)a[b]=g.div(a[b],a[c]);return a}function I(a){switch(a.length){case 0:return new e(g.parse(1));case 1:return new e([g.mul(a[0],-1),1]);default:var c=Math.floor(a.length/2),b=a.slice(c,a.length);return I(a.slice(0,c)).mul(I(b))}}var g={add:function(a,c){return a+c},sub:function(a,c){return a-c},mul:function(a,c){return a*c},div:function(a,c){if(0===c)throw"DIV/0";return a/c},parse:function(a){return parseFloat(a)},empty:function(a){return!a},
    pow:function(a,c){return Math.pow(a,c)},equals:function(a,c){return a==c}},Q=g,P=/([+-]?)(?:([^+x-]+)?(?:x(?:\^([\d\/]+))?)|([^+x-]+))/g;e.trace=null;e.prototype.coeff={};e.prototype.coeffArray=function(){for(var a=this.coeff,c=w(a),b=Array(c+1),d=0;d<=c;d++)a.hasOwnProperty(d)?b[d]=a[d]:b[d]=0;return b};e.prototype.gcd=function(a){var c=E(this.coeff);for(a=m(a);w(a)!==Number.NEGATIVE_INFINITY;){var b=E(c);H(b,a);c=a;a=b}a=G(c);return new e(N(c,a))};e.prototype.neg=function(){var a={},c=this.coeff,
    b;for(b in c)a[b]=g.mul(c[b],-1);return new e(a)};e.prototype.reciprocal=function(){var a={},c=this.coeff,b=w(c),d;for(d in c)a[b-d]=c[d];return new e(a)};e.prototype.eval=function(a){var c=this.coeff,b=w(c),d=c[b];for(--b;0<=b;b--)d=g.mul(d,a),g.empty(c[b])||(d=g.add(d,c[b]));return d};e.prototype.lc=function(){var a=G(this.coeff);return this.coeff[a]};e.prototype.lm=function(){var a=G(this.coeff),c={};c[a]=this.coeff[a];return new e(c)};e.prototype.monic=function(){return new e(N(E(this.coeff),
    G(this.coeff)))};e.prototype.add=function(a){a=m(a);var c={},b=this.coeff,d=M(a,b),f;for(f in d)c[f]=g.add(b[f]||0,a[f]||0);return new e(c)};e.prototype.sub=function(a){a=m(a);var c={},b=this.coeff,d=M(a,b),f;for(f in d)c[f]=g.sub(b[f]||0,a[f]||0);return new e(c)};e.prototype.mul=function(a){a=m(a);var c={},b=this.coeff;for(d in a){var d=+d;for(var f in b)f=+f,c[d+f]=g.add(c[d+f]||0,g.mul(a[d]||0,b[f]||0))}return new e(c)};e.prototype.addmul=function(a,c){var b=m(a),d=m(c),f={};for(p in b){var p=
    +p;for(var e in d)e=+e,f[p+e]=g.add(f[p+e]||0,g.mul(b[p]||0,d[e]||0))}return this.add(f)};e.prototype.div=function(a){return new e(H(E(this.coeff),m(a)))};e.prototype.pow=function(a){if(isNaN(a)||0>a||a%1)throw"Invalid";for(var c=new e(1),b=this;0<a;)a&1&&(c=c.mul(b)),b=b.mul(b),a>>=1;return c};e.prototype.mod=function(a){var c=E(this.coeff);H(c,m(a));return new e(c)};e.prototype.derive=function(a){if(void 0===a)a=1;else if(0>a)return null;var c=this.coeff,b={},d;for(d in c)+d>=a&&(b[d-a]=g.mul(c[d]||
    0,L(+d,a)));return new e(b)};e.prototype.integrate=function(a){if(void 0===a)a=1;else if(0>a)return null;var c=this.coeff,b={},d;for(d in c)b[+d+a]=g.div(c[d]||0,L(+d+a,a));return new e(b)};e.prototype.result=e.prototype.eval;e.fromRoots=function(a){var c=a.length,b=g.parse(0);a=a.filter(function(a){return!g.equals(a,b)});c-=a.length;a=I(a).coeff;var d={},f;for(f in a)d[c+parseInt(f,10)]=a[f];return new e(d)};e.prototype.complexRoots=function(a){for(var c=this.coeff,b=w(c),d=Array(b+1),f=Array(b),
    e=0;e<=b;e++)c.hasOwnProperty(e)?d[e]=n(c[e]):d[e]=n.ZERO;for(e=0;e<b;e++)f[e]=new n(a[e]);c=30;var k=Number.EPSILON,t=Number.MAX_VALUE;b=d.length-1;if(n.ZERO.equals(d[b]))throw"Inconsistent data: the leading coefficient is zero";if(n.ZERO.equals(d[0]))throw"The constant term is zero: deflate the polynomial";var g=0;f=Array(b+1);e=Array(b+1);for(var h=0;h<=b;h++)f[h]=d[h].abs(),g=Math.max(g,f[h]),e[h]=f[h];g>=t/(b+1)&&console.warn("WARNING: COEFFICIENTS TOO BIG, OVERFLOW IS LIKELY");for(h=0;h<=b;h++)e[b-
    h]=k*f[h]*(3.8*(b-h)+1),f[h]=k*f[h]*(3.8*h+1);0!=f[0]&&0!=f[b]||console.warn("WARNING: THE COMPUTATION OF SOME INCLUSION RADIUS MAY FAIL. THIS IS REPORTED BY RADIUS=0");k=Array(b);t=Array(b);for(h=0;h<b;h++)k[h]=!0,t[h]=0;void 0===c&&(c=30);var O=0;g=1;a:for(;g<=c;g++)for(h=0;h<b;h++)if(k[h]){var x=d,m=f,v=e;var u=a[h];var z=t[h];var q=x.length-1;var A=u.abs();if(1>=A){for(var l=x[q],y=l,r=m[q],B=q-1;1<=B;B--)l=l.mul(u).add(x[B]),y=y.mul(u).add(l),r=r*A+m[B];l=l.mul(u).add(x[0]);r=r*A+m[0];u=l.div(y);
    v=l.abs();(x=v>Number.MIN_VALUE+r)||(z=q*(v+r)/y.abs())}else{m=u.inverse();var C=1/A;y=l=x[0];r=v[q];for(B=q-1;1<=B;B--)l=l.mul(m).add(x[q-B]),y=y.mul(m).add(l),r=r*C+v[B];l=l.mul(m).add(x[q]);r=r*C+v[0];v=l.abs();x=v>Number.MIN_VALUE+r;l=l.mul(u).div(y);v=l.mul(q).sub(n.ONE);u=u.mul(l.div(v));x||(z=l.abs()+r*A/y.abs(),z=q*z/v.abs(),z*=A)}q={corr:u,again:x,radius:z};z=q.corr;k[h]=q.again;k[h]||(t[h]=q.radius);if(k[h]){q=a;A=h;y=q.length;r=q[A];u=n.ZERO;for(l=0;l<y;l++)l!=A&&(u=u.add(r.sub(q[l]).inverse()));
    a[h]=a[h].sub(z.div(n.ONE.sub(z.mul(u))))}else if(O++,O==b)break a}return{root:a,radius:t,err:k,iter:g}};e.prototype.toString=J("toString");e.prototype.toLatex=J("toLatex");e.prototype.toHorner=function(){function a(a,d){var b="";n&&a instanceof n?0===a.im?(0<a.re&&d&&(b+="+"),b+=a.re):0===a.re?(-1===a.im?b+="-":1!==a.im?(0<a.im&&d&&(b+="+"),b+=a.im):0<a.im&&d&&(b+="+"),b+="i"):(d&&(b+="+"),b=b+"("+a.toString(),b+=")"):(0<a&&d&&(b+="+"),b+=a.toString());return b}function c(d,f){var e=d.length-f-1,
    g=d[e]-(d[e-1]||0),h="",k="";0<g&&(h="x",1<g&&(h+="^"+g));0<e&&(h+=a(b[d[e-1]],!0));if(0===f)return a(b[d[e]],!1)+h;0<=e&&d[e]&&(k+="(");k+=c(d,f-1);0<=e&&d[e]&&(k+=")");return k+h}var b=this.coeff,d=[],f;for(f in b)g.empty(b[f])||d.push(+f);if(0===d.length)return"0";d.sort(function(a,d){return a-d});return c(d,d.length-1)};e.prototype.clone=function(){return new e(this)};e.prototype.degree=function(){return w(this.coeff)};e.setField=function(a){var c={Q:C,C:n,H:D}[a];if(void 0!==c)g={add:function(a,
    b){return(new c(a)).add(b)},sub:function(a,b){return(new c(a)).sub(b)},mul:function(a,b){return(new c(a)).mul(b)},div:function(a,b){return(new c(a)).div(b)},parse:function(a){return new c(a)},empty:function(a){return(new c(a)).equals(0)},pow:function(a,b){return(new c(a)).pow(b)},equals:function(a,b){return(new c(a)).equals(b)}};else if(!a||"R"===a)g=Q;else if("object"===typeof a)g=a;else if("Z"===a.charAt(0)){var b=+a.slice(1);g={add:function(a,c){return((a+c)%b+b)%b},sub:function(a,c){return((a-
    c)%b+b)%b},mul:function(a,c){return(a*c%b+b)%b},div:function(a,c){var d=c;for(var e=b,f=0,g=1,h=1,n=0;0!==d;){var m=e/d|0,w=e%d,v=f-h*m;m=g-n*m;e=d;d=w;f=h;g=n;h=v;n=m}d=[e,f,g];if(1!==d[0])throw"DIV/-";return(a*d[1]%b+b)%b},parse:function(a){return parseInt(a,10)},empty:function(a){return void 0===a||0===a},pow:function(a,c){for(var d=1;0<c;a=(a*a%b+b)%b,c>>=1)c&1&&(d=(d*a%b+b)%b);return d},equals:function(a,b){return a==b}}}};if("function"===typeof define&&define.amd)define(["fraction.js","complex.js",
    "quaternion"],function(a,c,b){C=a;n=c;D=b;return e});else if("object"===typeof exports){var C=require("fraction.js");var n=require("complex.js");var D=require("quaternion");module.exports=e}else C=F.Fraction,n=F.Complex,D=F.Quaternion,F.Polynomial=e})(this);